### Research Questions

Do colleges in the top quartile of academic selectivity (based on the incoming cohort's median ACT/SAT scores / acceptance rate) generate significantly different total athletic revenue than colleges in the bottom quartile?
* Rationale: This examines whether attracting highly competitive academic cohorts corresponds to a different scale of athletic financial operations.

How does the size of the incoming cohort moderate the relationship between total athletic recruiting expenses and total athletic revenue?
* Rationale: This explores the return on investment. Do schools bringing in massive freshman classes (often large state universities) see an exponential jump in athletic revenue for every dollar spent on recruiting, compared to schools bringing in small cohorts?
---

### Imports

In [1]:
import pandas as pd

---

### Variables

Identify which variables to keep (which variables will be the most useful/informative to answer the research questions posed above)

* College related data variables (`UNITID`, `OPEID`, `INSTNM`, `CITY`, `STABBR`, `ZIP`)
* `ADM_RATE`: admissions rate at each campus
* `SATVR25`: SAT 25th percentile for reading section
* `SATVR75`: SAT 75th percentile for reading section
* `SATMT25`: SAT 25th percentile for math
* `SATMT75`: SAT 75th percentile for math
* `ACTCM25`: ACT composite median 25th percentile
* `ACTCM75`: ACT composite median 75th percentile
* `ADMCON7`: indicates if test scores are required, recommended, considered but not required, or neither required nor recommended. 
* `UGDS`: number of degree/certificate-seeking undergraduates enrolled in the fall
* `CONTROL`: public vs private
* `ICLEVEL`: 2-year vs 4-year


Additional Variables:
* `MAIN`: 1 indictes the institution is the main campus, 0 indicates it is not
* `NUMBRANCH`: number of branches at the institution
* `TUITIONFEE_IN`: Tuition and required fees for in-district students
* `TUITIONFEE_OUT`: Tuition and required fees for out-of-state students
* `NPT4_PUB`: average net price for public institutions
* `NPT4_PRIV`: average net price for private institutions
* `PCTPELL`: proportion of low income students

In [2]:
cols = ['UNITID', 'OPEID', 'INSTNM', 'CITY', 'STABBR', 'ZIP', 'ADM_RATE', 'SATVR25', 
        'SATVR75', 'SATMT25', 'SATMT75', 'ACTCM25', 'ACTCM75', 'ADMCON7', 'UGDS', 
        'CONTROL', 'ICLEVEL', 'MAIN', 'NUMBRANCH', 'TUITIONFEE_IN', 'TUITIONFEE_OUT', 
        'NPT4_PUB', 'NPT4_PRIV', 'PCTPELL']
df = pd.read_csv('MERGED2023_24_PP.csv', usecols=cols)

df = df.rename(columns={'UNITID': 'unitid', 'OPEID': 'opeid', 'INSTNM': 'institution_name', 'CITY': 'city', 'STABBR': 'state', 
                        'ZIP': 'zip', 'ADM_RATE': 'admission_rate', 'SATVR25': 'SAT_reading25','SATVR75': 'SAT_reading75', 
                        'SATMT25': 'SAT_math25', 'SATMT75': 'SAT_math75', 'ACTCM25': 'ACT_median25', 'ACTCM75': 'ACT_median75', 
                        'ADMCON7': 'test_score_req', 'UGDS': 'num_undergrad', 'CONTROL': 'institution_type', 'ICLEVEL': 'institution_years', 
                        'MAIN': 'main_campus', 'NUMBRANCH': 'num_campuses', 'TUITIONFEE_IN': 'in_state_tuition', 
                        'TUITIONFEE_OUT': 'out_state_tuition', 'NPT4_PUB': 'avg_net_price_public', 'NPT4_PRIV': 'avg_net_price_private', 
                        'PCTPELL': 'prop_low_income'})

df

,unitid,opeid,institution_name,city,state,zip,main_campus,num_campuses,institution_type,admission_rate,...,ACT_median25,ACT_median75,num_undergrad,avg_net_price_public,avg_net_price_private,in_state_tuition,out_state_tuition,prop_low_income,institution_years,test_score_req
0,100654,100200.0,Alabama A & M University,Normal,AL,35762,1,1,1,0.6622,...,14.0,19.0,5726.0,14559.0,NaN,10024.0,18634.0,0.6441,1,5.0
1,100663,105200.0,University of Alabama at Birmingham,Birmingham,AL,35294-0110,1,1,1,0.8842,...,22.0,30.0,12118.0,17727.0,NaN,8832.0,21864.0,0.3318,1,5.0
2,100690,2503400.0,Amridge University,Montgomery,AL,36117-3553,1,1,2,NaN,...,NaN,NaN,226.0,NaN,NaN,NaN,NaN,0.6842,1,NaN
3,100706,105500.0,University of Alabama in Huntsville,Huntsville,AL,35899,1,1,1,0.7425,...,25.0,31.0,6650.0,19880.0,NaN,11770.0,24662.0,0.2250,1,5.0
4,100724,100500.0,Alabama State University,Montgomery,AL,36104-0271,1,1,1,0.9564,...,16.0,20.0,3322.0,13889.0,NaN,11248.0,19576.0,0.7203,1,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6425,49382201,4283601.0,College Unbound - Newport/Aquidneck Island,Newport,RI,028400000,0,2,2,NaN,...,NaN,NaN,NaN,NaN,NaN,10488.0,10488.0,NaN,1,NaN
6426,49425001,2609404.0,Valley College - Fairlawn - School of Nursing,Fairlawn,OH,443333631,0,3,3,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,NaN
6427,49501301,4247201.0,Western Maricopa Education Center - Southwest ...,Buckeye,AZ,85326-5705,0,3,1,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,NaN
6428,49501302,4247202.0,Western Maricopa Education Center - Northeast ...,Phoenix,AZ,85027-0000,0,3,1,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,NaN
6429,49664501,4285601.0,Burlington County Institute of Technology - Ad...,Medford,NJ,080550000,0,2,1,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,NaN

In [3]:
df["institution_type"] = df['institution_type'].map({1: 'public', 2: 'private nonprofit', 3: 'private for-profit'})
df

,unitid,opeid,institution_name,city,state,zip,main_campus,num_campuses,institution_type,admission_rate,...,ACT_median25,ACT_median75,num_undergrad,avg_net_price_public,avg_net_price_private,in_state_tuition,out_state_tuition,prop_low_income,institution_years,test_score_req
0,100654,100200.0,Alabama A & M University,Normal,AL,35762,1,1,public,0.6622,...,14.0,19.0,5726.0,14559.0,NaN,10024.0,18634.0,0.6441,1,5.0
1,100663,105200.0,University of Alabama at Birmingham,Birmingham,AL,35294-0110,1,1,public,0.8842,...,22.0,30.0,12118.0,17727.0,NaN,8832.0,21864.0,0.3318,1,5.0
2,100690,2503400.0,Amridge University,Montgomery,AL,36117-3553,1,1,private nonprofit,NaN,...,NaN,NaN,226.0,NaN,NaN,NaN,NaN,0.6842,1,NaN
3,100706,105500.0,University of Alabama in Huntsville,Huntsville,AL,35899,1,1,public,0.7425,...,25.0,31.0,6650.0,19880.0,NaN,11770.0,24662.0,0.2250,1,5.0
4,100724,100500.0,Alabama State University,Montgomery,AL,36104-0271,1,1,public,0.9564,...,16.0,20.0,3322.0,13889.0,NaN,11248.0,19576.0,0.7203,1,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6425,49382201,4283601.0,College Unbound - Newport/Aquidneck Island,Newport,RI,028400000,0,2,private nonprofit,NaN,...,NaN,NaN,NaN,NaN,NaN,10488.0,10488.0,NaN,1,NaN
6426,49425001,2609404.0,Valley College - Fairlawn - School of Nursing,Fairlawn,OH,443333631,0,3,private for-profit,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,NaN
6427,49501301,4247201.0,Western Maricopa Education Center - Southwest ...,Buckeye,AZ,85326-5705,0,3,public,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,NaN
6428,49501302,4247202.0,Western Maricopa Education Center - Northeast ...,Phoenix,AZ,85027-0000,0,3,public,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,NaN
6429,49664501,4285601.0,Burlington County Institute of Technology - Ad...,Medford,NJ,080550000,0,2,public,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,NaN

In [4]:
df["institution_years"] = df['institution_years'].map({1: '4-year', 2: '2-year', 3: 'Less-than-2-year'})
df

,unitid,opeid,institution_name,city,state,zip,main_campus,num_campuses,institution_type,admission_rate,...,ACT_median25,ACT_median75,num_undergrad,avg_net_price_public,avg_net_price_private,in_state_tuition,out_state_tuition,prop_low_income,institution_years,test_score_req
0,100654,100200.0,Alabama A & M University,Normal,AL,35762,1,1,public,0.6622,...,14.0,19.0,5726.0,14559.0,NaN,10024.0,18634.0,0.6441,4-year,5.0
1,100663,105200.0,University of Alabama at Birmingham,Birmingham,AL,35294-0110,1,1,public,0.8842,...,22.0,30.0,12118.0,17727.0,NaN,8832.0,21864.0,0.3318,4-year,5.0
2,100690,2503400.0,Amridge University,Montgomery,AL,36117-3553,1,1,private nonprofit,NaN,...,NaN,NaN,226.0,NaN,NaN,NaN,NaN,0.6842,4-year,NaN
3,100706,105500.0,University of Alabama in Huntsville,Huntsville,AL,35899,1,1,public,0.7425,...,25.0,31.0,6650.0,19880.0,NaN,11770.0,24662.0,0.2250,4-year,5.0
4,100724,100500.0,Alabama State University,Montgomery,AL,36104-0271,1,1,public,0.9564,...,16.0,20.0,3322.0,13889.0,NaN,11248.0,19576.0,0.7203,4-year,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6425,49382201,4283601.0,College Unbound - Newport/Aquidneck Island,Newport,RI,028400000,0,2,private nonprofit,NaN,...,NaN,NaN,NaN,NaN,NaN,10488.0,10488.0,NaN,4-year,NaN
6426,49425001,2609404.0,Valley College - Fairlawn - School of Nursing,Fairlawn,OH,443333631,0,3,private for-profit,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Less-than-2-year,NaN
6427,49501301,4247201.0,Western Maricopa Education Center - Southwest ...,Buckeye,AZ,85326-5705,0,3,public,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Less-than-2-year,NaN
6428,49501302,4247202.0,Western Maricopa Education Center - Northeast ...,Phoenix,AZ,85027-0000,0,3,public,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Less-than-2-year,NaN
6429,49664501,4285601.0,Burlington County Institute of Technology - Ad...,Medford,NJ,080550000,0,2,public,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Less-than-2-year,NaN

In [5]:
df['test_score_req'] = df['test_score_req'].map({1: 'Required', 2: 'Recommended', 3: 'Neither required nor recommended',
                                                 4: 'Do not know', 5: 'Considered but not required'})
df['test_score_req']

0       Considered but not required
1       Considered but not required
2                               NaN
3       Considered but not required
4       Considered but not required
                   ...
6425                            NaN
6426                            NaN
6427                            NaN
6428                            NaN
6429                            NaN
Name: test_score_req, Length: 6430, dtype: object

In [6]:
df.isna().sum()

unitid                      0
opeid                      25
institution_name            0
city                        0
state                       0
zip                         0
main_campus                 0
num_campuses                0
institution_type            0
admission_rate           4484
SAT_reading25            5436
SAT_reading75            5436
SAT_math25               5436
SAT_math75               5436
ACT_median25             5457
ACT_median75             5457
num_undergrad             773
avg_net_price_public     4624
avg_net_price_private    3070
in_state_tuition         2700
out_state_tuition        2700
prop_low_income           818
institution_years           0
test_score_req           4458
dtype: int64

In [7]:
df['institution_name'] = df['institution_name'].str.lower()
df['city'] = df['city'].str.lower()
df

,unitid,opeid,institution_name,city,state,zip,main_campus,num_campuses,institution_type,admission_rate,...,ACT_median25,ACT_median75,num_undergrad,avg_net_price_public,avg_net_price_private,in_state_tuition,out_state_tuition,prop_low_income,institution_years,test_score_req
0,100654,100200.0,alabama a & m university,normal,AL,35762,1,1,public,0.6622,...,14.0,19.0,5726.0,14559.0,NaN,10024.0,18634.0,0.6441,4-year,Considered but not required
1,100663,105200.0,university of alabama at birmingham,birmingham,AL,35294-0110,1,1,public,0.8842,...,22.0,30.0,12118.0,17727.0,NaN,8832.0,21864.0,0.3318,4-year,Considered but not required
2,100690,2503400.0,amridge university,montgomery,AL,36117-3553,1,1,private nonprofit,NaN,...,NaN,NaN,226.0,NaN,NaN,NaN,NaN,0.6842,4-year,NaN
3,100706,105500.0,university of alabama in huntsville,huntsville,AL,35899,1,1,public,0.7425,...,25.0,31.0,6650.0,19880.0,NaN,11770.0,24662.0,0.2250,4-year,Considered but not required
4,100724,100500.0,alabama state university,montgomery,AL,36104-0271,1,1,public,0.9564,...,16.0,20.0,3322.0,13889.0,NaN,11248.0,19576.0,0.7203,4-year,Considered but not required
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6425,49382201,4283601.0,college unbound - newport/aquidneck island,newport,RI,028400000,0,2,private nonprofit,NaN,...,NaN,NaN,NaN,NaN,NaN,10488.0,10488.0,NaN,4-year,NaN
6426,49425001,2609404.0,valley college - fairlawn - school of nursing,fairlawn,OH,443333631,0,3,private for-profit,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Less-than-2-year,NaN
6427,49501301,4247201.0,western maricopa education center - southwest ...,buckeye,AZ,85326-5705,0,3,public,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Less-than-2-year,NaN
6428,49501302,4247202.0,western maricopa education center - northeast ...,phoenix,AZ,85027-0000,0,3,public,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Less-than-2-year,NaN
6429,49664501,4285601.0,burlington county institute of technology - ad...,medford,NJ,080550000,0,2,public,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Less-than-2-year,NaN

In [8]:
df.to_csv('2023-24_cleaned_admissions_data.csv')